
version: '3.5'
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: sh ./docker-start-dev.sh
  #   env_file:
  #     - '.env'
  #   volumes:
  #     - .:/home/app
  #     - /home/app/node_modules
  #   ports:
  #     - "3333:3333"
  #   networks:
  #     - local_network
  #   depends_on:
  #     - mysql_db

  mysql_db:
    container_name: "${APP_NAME}-mysqldb"
    image: mysql:8
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    env_file:
      - '.env'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sort_buffer_size=1073741824
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      local_network:

volumes:
  mysql:
  mysql_config:

networks:
  local_network:
    driver: bridge
